const stressIncidents = [
    {
        Index: 0,
        Reason: "Work",
        Date: "04/20/2020",
        Time: "3:31 PM",
        Stress: "High",
        StressScore: 3,
        Description: "Work related high stress incident occurred",
    },
    {
        Index: 1,
        Reason: "Work",
        Date: "04/11/2020",
        Time: "2:20 PM",
        Stress: "Moderate",
        StressScore: 2,
        Description: "Work related high stress incident occurred",
    },
    {
        Index: 2,
        Reason: "Family",
        Date: "04/01/2020",
        Time: "9:42 PM",
        Stress: "High",
        StressScore: 3,
        Description: "Family related high stress incident occurred",
    },
    {
        Index: 3,
        Reason: "Work",
        Date: "03/31/2020",
        Time: "3:20 PM",
        Stress: "Moderate",
        StressScore: 2,
        Description: "Work related high stress incident occurred",
    },
    {
        Index: 4,
        Reason: "Social",
        Date: "03/27/2020",
        Time: "7:45 PM",
        Stress: "Moderate",
        StressScore: 2,
        Description: "Social related high stress incident occurred",
    },
    {
        Index: 5,
        Reason: "Family",
        Date: "03/21/2019",
        Time: "8:10 AM",
        Stress: "High",
        StressScore: 3,
        Description: "Family related high stress incident occurred",
    },
]

export default stressIncidents;